default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] || "exp_pg" %>
  password: <%= Rails.application.credentials.database[:password] %>
  port: <%= "5432" %>
  host: <%= "127.0.0.1" %>
development:
  <<: *default
  database: exp_development
  port: 5432
test:
  <<: *default
  database: exp_test
  port: 5432
production:
  <<: *default
  database: exp_production
  username: exp_pg
  password: <%= ENV['EXP_DATABASE_PASSWORD'] %>